# Generated by Django 5.1.1 on 2024-09-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/profile.jpeg', null=True, upload_to='images'),
        ),
    ]
