# Generated by Django 5.1.1 on 2024-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/profiles/profile.jpeg', null=True, upload_to='images/profiles'),
        ),
    ]
