# Generated by Django 5.1.1 on 2024-09-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_user_image_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
